#!/bin/bash

clear

RED='\033[0;31m'
GRN='\033[0;32m'
CYN='\033[0;36m'
YEL='\033[1;33m'
NC='\033[0m'

echo -e "${YEL}"
cat << "EOF"
██████╗ ███████╗███████╗██████╗ ███████╗██████╗ 
██╔══██╗██╔════╝██╔════╝██╔══██╗██╔════╝██╔══██╗
██████╔╝█████╗  █████╗  ██║  ██║█████╗  ██████╔╝
██╔══██╗██╔══╝  ██╔══╝  ██║  ██║██╔══╝  ██╔══██╗
██████╔╝███████╗███████╗██████╔╝███████╗██║  ██║
╚═════╝ ╚══════╝╚══════╝╚═════╝ ╚══════╝╚═╝  ╚═╝
              B E E D E R C L O U D
EOF
echo -e "${NC}"

echo -e "${GRN}Installing Docker & Compose...${NC}"

apt update
apt install docker.io docker-compose -y
systemctl enable docker
systemctl start docker

mkdir -p /home/pterodactyl/panel
cd /home/pterodactyl/panel

echo -e "${CYN}Creating docker-compose.yml...${NC}"

cat <<EOF > docker-compose.yml
version: "3"

services:

  database:
    image: mariadb:10.5
    container_name: panel_database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pterodactylroot
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: pterodactyl

  cache:
    image: redis:alpine
    container_name: panel_cache
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: panel_panel
    restart: always
    ports:
      - "8030:80"
    depends_on:
      - database
      - cache
    volumes:
      - ./data/var:/app/var
      - ./data/logs:/app/storage/logs
      - ./data/nginx:/etc/nginx/http.d
      - ./data/certs:/etc/letsencrypt
    environment:
      APP_URL: http://localhost:8030
      APP_TIMEZONE: UTC
      APP_SERVICE_AUTHOR: admin@example.com
      TRUSTED_PROXIES: "*"

      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: pterodactyl
      DB_SSL: "false"

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: cache
EOF

mkdir -p data/{database,var,logs,nginx,certs}

echo -e "${GRN}Starting containers...${NC}"

docker-compose up -d

echo -e "${YEL}Waiting database start...${NC}"
sleep 20

echo -e "${GRN}Running database migration...${NC}"

docker exec -it panel_panel php artisan migrate --seed --force

echo -e "${GRN}Create Admin User${NC}"

docker exec -it panel_panel php artisan p:user:make

echo -e "${GRN}Panel installed!${NC}"
echo -e "${CYN}Open panel:${NC} http://YOUR_SERVER_IP:8030"
