#!/bin/bash

clear

RED='\033[0;31m'
GRN='\033[0;32m'
CYN='\033[0;36m'
YEL='\033[1;33m'
NC='\033[0m'

echo -e "${YEL}"
cat << "EOF"
██████╗ ███████╗███████╗██████╗ ███████╗██████╗ 
██╔══██╗██╔════╝██╔════╝██╔══██╗██╔════╝██╔══██╗
██████╔╝█████╗  █████╗  ██║  ██║█████╗  ██████╔╝
██╔══██╗██╔══╝  ██╔══╝  ██║  ██║██╔══╝  ██╔══██╗
██████╔╝███████╗███████╗██████╔╝███████╗██║  ██║
╚═════╝ ╚══════╝╚══════╝╚═════╝ ╚══════╝╚═╝  ╚═╝
            B E E D E R C L O U D
EOF
echo -e "${NC}"

echo -e "${YEL}Installing Docker...${NC}"

apt update
apt install docker.io -y
systemctl enable docker
systemctl start docker

echo -e "${YEL}Removing broken docker-compose v1...${NC}"

apt remove docker-compose -y 2>/dev/null
rm -f /usr/bin/docker-compose

echo -e "${YEL}Installing Docker Compose v2...${NC}"

apt install docker-compose-plugin -y

echo -e "${YEL}Cleaning old containers...${NC}"

docker rm -f $(docker ps -aq) 2>/dev/null
docker system prune -a -f

mkdir -p /home/pterodactyl/panel
cd /home/pterodactyl/panel

echo -e "${CYN}Creating docker-compose.yml...${NC}"

cat <<EOF > docker-compose.yml
services:

  database:
    image: mariadb:10.5
    container_name: panel_database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: pterodactyl

  cache:
    image: redis:alpine
    container_name: panel_cache
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:v1.11
    container_name: panel_panel
    restart: always
    ports:
      - "8030:80"
    depends_on:
      - database
      - cache
    volumes:
      - ./data/var:/app/var
      - ./data/logs:/app/storage/logs
    environment:
      APP_URL: http://localhost:8030
      APP_TIMEZONE: UTC
      TRUSTED_PROXIES: "*"

      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: pterodactyl
      DB_SSL: "false"

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: cache
EOF

mkdir -p data/{database,var,logs}

echo -e "${GRN}Starting containers...${NC}"

docker compose up -d

echo -e "${YEL}Waiting database start...${NC}"
sleep 25

echo -e "${GRN}Running database migration...${NC}"

docker exec -it panel_panel php artisan migrate --seed --force

echo -e "${GRN}Create Admin User${NC}"

docker exec -it panel_panel php artisan p:user:make

echo -e "${GRN}Panel installed!${NC}"
echo -e "${CYN}Open panel:${NC} http://YOUR_SERVER_IP:8030"
